networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.55.1
        subnet: 192.168.55.0/24
      driver: default
services:
  node0:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 0
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.10
    ports:
    - 9090:9090
  node1:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 1
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.11
    ports:
    - 9091:9091
  node2:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 2
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.12
    ports:
    - 9092:9092
  node3:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 3
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.13
    ports:
    - 9093:9093
  node4:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 4
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.14
    ports:
    - 9094:9094
  node5:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 5
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.15
    ports:
    - 9095:9095
  node6:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 6
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.16
    ports:
    - 9096:9096
  node7:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 7
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.17
    ports:
    - 9097:9097
  node8:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 8
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.18
    ports:
    - 9098:9098
  node9:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 9
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.19
    ports:
    - 9099:9099
  node10:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 10
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.20
    ports:
    - 9100:9100
  node11:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 11
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.21
    ports:
    - 9101:9101
  node12:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 12
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.22
    ports:
    - 9102:9102
  node13:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 13
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.23
    ports:
    - 9103:9103
  node14:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 14
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.24
    ports:
    - 9104:9104
  node15:
    build: .
    environment:
      ALGORITHM: cluster
      EMPTY: null
      PID: 15
      TOPOLOGY: topologies/cluster.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.25
    ports:
    - 9105:9105
version: '3.7'
x-common-variables:
  EMPTY: null
  TOPOLOGY: topologies/cluster.yaml
